"""Noticias de la bolsa.

Cada noticia tiene un titular, un cuerpo y sus efectos: qué valores se mueven y hacia dónde (+1 sube, -1 baja) si la
noticia resulta ser cierta. El primero de los efectos es el principal y se mueve con el tamaño de la noticia; los
demás, un tamaño menos. Las noticias sin efectos son ruido: suenan importantes pero no mueven nada.

Tamaños: "N" normal (+10-30%), "I" importante (~x2), "B" bombazo (~x5).
`trap`: el titular engaña y hay que leer el cuerpo (solo para la documentación, el juego no lo usa).
"""


def N(title, body, effects, size="N", trap=False):
    return {"title": title, "body": body, "effects": effects, "size": size if effects else None, "trap": trap}


NEWS = {
    # ================================================================== ORO
    "ORO": [
        N("El banco central sorprende con una subida de tipos mayor de lo esperado",
          "Medio punto de golpe, cuando el mercado esperaba un cuarto. «Tener el dinero quieto va a salir caro», "
          "resumía un analista mientras los depósitos volvían a pagar intereses.",
          {"ORO": -1, "BTC": -1, "BAN": 1}, "I"),
        N("Varios bancos centrales asiáticos duplican sus compras de lingotes",
          "Las cámaras acorazadas de Singapur y Bombay trabajan a doble turno. Según fuentes del sector, la orden es "
          "«reducir la dependencia del dólar cueste lo que cueste».",
          {"ORO": 1}, "I"),
        N("Se rompen las conversaciones de paz entre dos potencias fronterizas",
          "Las delegaciones abandonaron la mesa tras once horas de reunión. Varias embajadas recomiendan a sus "
          "ciudadanos no viajar a la región.",
          {"ORO": 1, "PTR": 1, "TUR": -1}, "I"),
        N("Buenas noticias para el bolsillo: la inflación baja por tercer mes seguido",
          "Los precios de la cesta de la compra se estabilizan y el dólar marca su mejor semana del año. Quien "
          "guardaba sus ahorros «por miedo a la inflación» empieza a respirar tranquilo.",
          {"ORO": -1}, "N", trap=True),
        N("Huelga indefinida en las tres grandes minas de una productora sudafricana",
          "Los mineros piden un 20% más de sueldo. La empresa asegura que «no hay prisa por negociar», mientras los "
          "camiones de mineral se acumulan a la entrada.",
          {"ORO": 1}),
        N("Hallan un yacimiento de oro «de los que salen una vez por generación»",
          "Los geólogos calculan que la mina del Yukón podría aumentar un 15% la producción mundial en pocos años. "
          "Tres grandes mineras ya pujan por los derechos de explotación.",
          {"ORO": -1}, "B"),
        N("Los fondos de pensiones se deshacen de los activos «que no dan rendimiento»",
          "Los gestores prefieren bonos que paguen intereses. «Un lingote no reparte dividendos», recordaba el "
          "director de uno de los mayores fondos del país.",
          {"ORO": -1}),
        N("Las joyerías indias agotan existencias antes de la temporada de bodas",
          "En algunos mercados de Jaipur ya hay lista de espera para encargar collares. Las familias compran ahora "
          "por miedo a que el precio suba todavía más.",
          {"ORO": 1}),
        N("El presidente de la Reserva insinúa que «el trabajo contra la inflación no ha terminado»",
          "Fue una sola frase al final de una conferencia bastante aburrida, pero los operadores entendieron el "
          "mensaje: habrá más subidas de tipos.",
          {"ORO": -1}),
        N("Rumores de impago en la deuda de un país de la eurozona",
          "El ministro de Finanzas lo niega, pero sus bonos se desploman y los ahorradores sacan dinero de los bancos "
          "del país. Las agencias de viajes ya notan cancelaciones.",
          {"ORO": 1, "TUR": -1}, "I"),
        N("El oro, «el activo favorito de los abuelos», según un estudio",
          "La encuesta, hecha a 1.200 personas mayores de 70 años, revela también que el 64% guarda billetes debajo "
          "del colchón. Los autores no sacan ninguna conclusión sobre el mercado.",
          {}),
        N("El mayor banco suizo recomienda a sus clientes «diversificar en refugio»",
          "La nota interna, filtrada a la prensa, aconseja a las grandes fortunas guardar parte de su patrimonio en "
          "metales «por lo que pueda pasar».",
          {"ORO": 1}),
        N("Alto el fuego inesperado en la región más caliente del planeta",
          "Ambos bandos firmaron de madrugada en un hotel de la costa. Las aerolíneas ya estudian reabrir las rutas "
          "que suspendieron hace meses.",
          {"ORO": -1, "PTR": -1, "TUR": 1}, "I"),
        N("Malas noticias para la minería: se inunda la mayor mina de oro del mundo",
          "El agua ha anegado las galerías más profundas y la producción se detendrá al menos medio año. Las "
          "aseguradoras ya hablan de pérdidas millonarias.",
          {"ORO": 1}, "N", trap=True),
        N("Las bolsas mundiales marcan máximos por quinto día consecutivo",
          "El optimismo es general: los inversores venden lo que compraron «por si acaso» para meterse en acciones "
          "que no paran de subir.",
          {"ORO": -1}),
        N("Un fondo soberano vende la mitad de sus reservas de metales",
          "Necesita liquidez para pagar el aeropuerto más grande de Oriente Medio: siete pistas, un hotel de 2.000 "
          "habitaciones y una pista de esquí cubierta.",
          {"ORO": -1}),
        N("Colas en las tiendas de compraventa de oro tras una devaluación sorpresa",
          "Tres países devaluaron su moneda el mismo fin de semana. En sus capitales, la gente cambia sus ahorros por "
          "monedas de oro, anillos y cadenas.",
          {"ORO": 1}, "I"),
        N("Revolución en el reciclaje: sacan oro de los móviles viejos a un coste ridículo",
          "Un laboratorio noruego recupera el metal de los circuitos con un baño químico barato. Se calcula que hay "
          "5.000 millones de teléfonos olvidados en los cajones.",
          {"ORO": -1}, "I", trap=True),
        N("Los bancos vuelven a ofrecer depósitos al 6%",
          "«Por fin el dinero en cuenta da algo», celebra una asociación de ahorradores. Las colas en las oficinas "
          "recuerdan a otras épocas.",
          {"ORO": -1, "BAN": 1}),
        N("Un analista de televisión asegura que el oro «brilla más en otoño»",
          "Lo dijo en un programa matinal, entre una receta de croquetas y el horóscopo. No aportó ningún dato.",
          {}),
    ],
    # ================================================================== PTR
    "PTR": [
        N("Varias navieras desvían sus buques por el cabo de Buena Esperanza",
          "Tras dos incidentes en el estrecho, las grandes compañías prefieren rodear África: diez días más de viaje y "
          "miles de toneladas más de combustible por barco.",
          {"PTR": 1, "NAV": 1}, "I"),
        N("El cartel de productores recorta 2 millones de barriles diarios",
          "La reunión duró apenas veinte minutos. «Mantendremos la disciplina», dijo el portavoz antes de marcharse "
          "sin aceptar preguntas.",
          {"PTR": 1}, "I"),
        N("Un huracán de categoría 4 se dirige al golfo",
          "Las petroleras evacúan a los trabajadores de las plataformas marinas. Los meteorólogos esperan que toque "
          "tierra en 48 horas.",
          {"PTR": 1}, "I"),
        N("Los depósitos de crudo, llenos por sexta semana consecutiva",
          "Los tanques de Oklahoma están al 92%. Algunos operadores ya alquilan petroleros para usarlos como "
          "almacenes flotantes.",
          {"PTR": -1}),
        N("Un gran productor se salta las cuotas y bombea a máxima capacidad",
          "«Nadie nos dice cuánto podemos vender», declaró su ministro de Energía. El resto del cartel convoca una "
          "reunión de urgencia.",
          {"PTR": -1}, "I"),
        N("Los coches eléctricos superan por primera vez a los de gasolina en Europa",
          "Ocurrió en marzo y en catorce países. Las gasolineras de autopista empiezan a instalar cargadores "
          "rápidos junto a los surtidores.",
          {"PTR": -1, "VRD": 1}),
        N("Explota un oleoducto que transporta el 8% del crudo del continente",
          "Las llamas se veían a cuarenta kilómetros. Los técnicos calculan que la reparación llevará «muchas "
          "semanas» y no existe una ruta alternativa.",
          {"PTR": 1}, "B"),
        N("China anuncia un plan de estímulo industrial «sin precedentes»",
          "Carreteras, fábricas y centros de datos: el plan equivale al 4% de su economía y empieza a aplicarse este "
          "mismo trimestre.",
          {"PTR": 1, "SEMI": 1}, "I"),
        N("El queroseno, por las nubes: las aerolíneas recortan vuelos",
          "Las compañías de bajo coste eliminan 300 rutas este verano y las que se mantienen suben precios. Las "
          "petroleras, en cambio, no notarán nada: los aviones son una parte mínima de lo que venden.",
          {"TUR": -1}, "N", trap=True),
        N("Se levantan las sanciones a un gran exportador de crudo",
          "Después de seis años, sus petroleros vuelven a salir del puerto. Tiene almacenados 90 millones de "
          "barriles listos para vender.",
          {"PTR": -1}, "I"),
        N("Un invierno más suave de lo normal en el norte",
          "En Escandinavia se ha visto gente en manga corta en enero. Las calefacciones apenas se han encendido y "
          "las eléctricas venden menos que nunca.",
          {"PTR": -1, "VRD": -1}),
        N("Un ministro asegura que «el petróleo seguirá siendo importante durante años»",
          "La frase, pronunciada en la inauguración de una rotonda, ha dado mucho que hablar en las redes. Nadie "
          "sabe muy bien a qué venía.",
          {}),
        N("Las refinerías cierran por mantenimiento antes del verano",
          "Mientras estén paradas no comprarán ni un barril de crudo. Las revisiones durarán entre tres y cinco "
          "semanas.",
          {"PTR": -1}, "N", trap=True),
        N("Fallos estructurales en la mayor terminal de carga de crudo del mundo",
          "Los ingenieros han prohibido atracar a los grandes petroleros. Decenas de barcos esperan fondeados sin "
          "poder cargar.",
          {"PTR": 1, "NAV": -1}),
        N("Récord de demanda de gasolina en el puente",
          "Las autopistas se colapsaron desde el jueves por la tarde y algunas estaciones de servicio de la costa se "
          "quedaron sin combustible el sábado.",
          {"PTR": 1, "TUR": 1}),
        N("Aparecen minas flotantes en el estrecho por el que pasa un tercio del crudo marítimo",
          "La marina tardará días en limpiar la zona. Los cruceros cancelan sus escalas y los petroleros esperan a "
          "ambos lados.",
          {"PTR": 1, "NAV": 1, "TUR": -1}, "I"),
        N("Un virus informático paraliza las ventas de la mayor petrolera estatal",
          "Los atacantes han cifrado sus sistemas de facturación. Ningún barco puede cargar hasta que se "
          "restablezcan los contratos.",
          {"PTR": 1}),
        N("La agencia de la energía prevé un año «tranquilo y estable»",
          "El informe apunta a fábricas que producen menos y a coches que gastan menos. «No es una caída de la "
          "demanda, es una pausa», matizan sus autores.",
          {"PTR": -1}, "N", trap=True),
        N("Una ley obliga a mezclar un 20% de biocombustible en la gasolina",
          "El combustible se fabricará con maíz y caña de azúcar. Los agricultores celebran la medida; las "
          "petroleras ya preparan el recurso.",
          {"PTR": -1, "AGR": 1}),
        N("Las petroleras celebran su congreso anual con récord de asistentes",
          "Hubo 18.000 inscritos, un concierto y una exposición de cascos antiguos. Las conferencias, según varios "
          "asistentes, «fueron las de siempre».",
          {}),
    ],
    # ================================================================== NAV
    "NAV": [
        N("Una sequía histórica deja el canal con la mitad de calado",
          "Solo pueden cruzar barcos medio vacíos y la espera ya supera las tres semanas. Los fletes se disparan en "
          "todas las rutas.",
          {"NAV": 1}, "I"),
        N("Los astilleros coreanos entregan una flota récord de portacontenedores",
          "Son 140 barcos nuevos en un solo año, muchos más de los que necesita el comercio mundial. Habrá que "
          "llenarlos de alguna manera.",
          {"NAV": -1}),
        N("Huelga general de estibadores en los puertos de la costa este",
          "Los barcos de la Naviera Atlántica esperan sin descargar y pagan cada día de amarre. Varios clientes "
          "amenazan con cambiar de transportista.",
          {"NAV": -1}),
        N("El índice de fletes marítimos sube por cuarta semana",
          "Enviar un contenedor de Shanghái a Róterdam cuesta ya el doble que en primavera.",
          {"NAV": 1}),
        N("Se prevé la mejor campaña navideña de la década",
          "Jugueterías y tiendas de electrónica hacen pedidos récord a sus fábricas de Asia para tener las "
          "estanterías llenas a tiempo.",
          {"NAV": 1, "SEMI": 1}),
        N("Dos grandes rivales de la Naviera Atlántica se alían para compartir rutas",
          "Llenarán más sus barcos y bajarán los precios a los clientes. «Es una declaración de guerra de tarifas», "
          "admiten en el sector.",
          {"NAV": -1}),
        N("Los piratas vuelven a la ruta más transitada de África oriental",
          "Tres asaltos en un mes. Las aseguradoras disparan las primas y muchos barcos prefieren rodear la zona.",
          {"NAV": 1, "PTR": 1}),
        N("Las fábricas asiáticas reducen pedidos por la caída del consumo occidental",
          "Menos ventas en las tiendas de Europa y América significa menos contenedores y menos chips. Varios "
          "polígonos industriales eliminan turnos.",
          {"NAV": -1, "SEMI": -1}, "I"),
        N("Golpe a las navieras: obligadas a navegar más despacio para contaminar menos",
          "La norma reduce la velocidad máxima un 20%. Cada viaje durará más días y harán falta más barcos para "
          "transportar la misma carga.",
          {"NAV": 1}, "N", trap=True),
        N("Un gigante del comercio online fabricará cerca de sus clientes",
          "Abrirá veinte fábricas en Europa y América para dejar de depender de los envíos desde Asia.",
          {"NAV": -1}),
        N("El nuevo director de la naviera promete «una nueva era de eficiencia»",
          "En su primer discurso habló durante cuarenta minutos sin dar ni una cifra. Los empleados recibieron una "
          "taza con el logotipo nuevo.",
          {}),
        N("Un portacontenedores encallado bloquea el canal",
          "Mide 400 metros y está atravesado de orilla a orilla. Más de 300 barcos esperan y los remolcadores no "
          "consiguen moverlo.",
          {"NAV": 1, "PTR": 1}, "B"),
        N("Buenas noticias para los astilleros: el acero se desploma",
          "Construir un portacontenedores sale un 25% más barato. Los armadores aprovechan para encargar barcos "
          "nuevos, y en unos meses sobrará espacio en todas las rutas.",
          {"NAV": -1}, "N", trap=True),
        N("Un tifón cierra los tres mayores puertos del sur de China",
          "Las fábricas de electrónica no pueden enviar su producción. Cuando los puertos reabran habrá cola para "
          "conseguir sitio en un barco.",
          {"NAV": 1, "SEMI": -1}, "I"),
        N("Se firma un tratado de libre comercio entre dos bloques enormes",
          "Quedan eliminados los aranceles de 9.000 productos. Los exportadores ya preparan los primeros envíos.",
          {"NAV": 1}, "I"),
        N("Las aseguradoras multiplican por diez las primas de los barcos en el golfo",
          "Las navieras repercuten el coste a sus clientes con un «recargo de riesgo», y los petroleros que no "
          "quieren pagar dan un rodeo de varios días.",
          {"NAV": 1, "PTR": 1}, "N", trap=True),
        N("Un ciberataque paraliza los puertos del norte de Europa",
          "Las grúas automáticas están paradas y los contenedores se apilan en los muelles de Róterdam y Hamburgo. "
          "La naviera no puede cargar ni descargar.",
          {"NAV": -1}),
        N("El combustible marítimo cae a mínimos de cinco años",
          "Es el mayor gasto de una naviera: más de la mitad de lo que cuesta cada viaje.",
          {"NAV": 1}),
        N("Un tren unirá China y Europa en 12 días",
          "El nuevo corredor ferroviario promete llevar contenedores en la mitad de tiempo que un barco. Ya hay 40 "
          "trenes semanales reservados.",
          {"NAV": -1}, "I"),
        N("Los contenedores vacíos se acumulan en los puertos americanos",
          "Nadie los necesita: hay pilas de seis alturas en Los Ángeles. Las navieras los devuelven a Asia sin carga.",
          {"NAV": -1}),
    ],
    # ================================================================== SEMI
    "SEMI": [
        N("Un gigante asiático construirá la mayor fábrica de chips del mundo",
          "Será tres veces mayor que cualquier otra y empezará a producir el año que viene. Los expertos temen que el "
          "mercado se inunde de chips baratos.",
          {"SEMI": -1}, "I", trap=True),
        N("Restringen la exportación de las máquinas de litografía más avanzadas",
          "Sin ellas no se pueden fabricar los chips más modernos. Los fabricantes que ya las tienen podrán subir "
          "sus precios.",
          {"SEMI": 1}),
        N("Un terremoto paraliza la mayor fundición de chips de la isla",
          "La planta fabrica uno de cada cuatro procesadores avanzados del mundo. Las salas limpias están dañadas y "
          "no hay fecha de reapertura.",
          {"SEMI": 1}, "B"),
        N("Las ventas de móviles caen por segundo trimestre consecutivo",
          "La gente ya aguanta su teléfono cuatro años de media. Los fabricantes reducen sus pedidos de procesadores.",
          {"SEMI": -1}),
        N("Las grandes tecnológicas triplican su gasto en centros de datos",
          "Necesitan chips para entrenar sus modelos de inteligencia artificial, y han firmado contratos para "
          "alimentar los nuevos centros únicamente con energía solar y eólica.",
          {"SEMI": 1, "VRD": 1}, "I"),
        N("Descubren una vulnerabilidad grave en una familia de procesadores",
          "Afecta a cientos de millones de ordenadores. El parche reduce el rendimiento un 15% y ya hay demandas en "
          "tres países.",
          {"SEMI": -1}),
        N("La escasez de agua amenaza a las fábricas de obleas del desierto",
          "Fabricar chips necesita millones de litros de agua ultrapura al día. Dos plantas ya han reducido su "
          "producción.",
          {"SEMI": 1}),
        N("Las consolas de nueva generación se retrasan un año",
          "Los fabricantes no llegan a tiempo con el diseño. Los pedidos de chips previstos para otoño se cancelan y "
          "los estudios reorganizan sus lanzamientos.",
          {"SEMI": -1, "VID": -1}),
        N("Competencia para la industria: un fabricante de coches diseñará sus propios chips",
          "Pero alguien tendrá que fabricárselos: ya ha firmado un contrato de diez años con dos fundiciones "
          "asiáticas para toda su producción.",
          {"SEMI": 1}, "N", trap=True),
        N("Los almacenes de memorias, a rebosar",
          "Los distribuidores acumulan cuatro meses de inventario y empiezan a vender con descuento.",
          {"SEMI": -1}),
        N("Un gurú tecnológico dice que «el silicio es el nuevo petróleo»",
          "Lo dijo con camiseta negra y vaqueros ante 3.000 personas que aplaudieron mucho. Después presentó una "
          "nevera con pantalla.",
          {}),
        N("Subvenciones millonarias para fabricar chips en casa",
          "El gobierno pagará hasta la mitad de cada fábrica nueva. Ya hay seis empresas haciendo cola en el "
          "ministerio.",
          {"SEMI": 1}, "I"),
        N("Guerra de precios entre los dos grandes fabricantes de tarjetas gráficas",
          "Cada uno ha rebajado sus modelos un 30% en una semana. Los márgenes se evaporan.",
          {"SEMI": -1}),
        N("Los mineros de criptomonedas compran todas las tarjetas gráficas",
          "Las tiendas online se quedan sin existencias en horas. Los foros de jugadores están que arden.",
          {"SEMI": 1, "BTC": 1}),
        N("Se cancela el mayor salón tecnológico del año",
          "Iba a ser el escaparate de los productos de la temporada. Muchos lanzamientos se aplazan sin fecha.",
          {"SEMI": -1}),
        N("Un apagón obliga a tirar miles de obleas",
          "Seis horas sin luz en el polo tecnológico del norte. Todo lo que estaba a medio fabricar ya no sirve.",
          {"SEMI": 1}),
        N("Los fabricantes de portátiles cancelan pedidos",
          "Las ventas de la vuelta al cole han sido flojas y los almacenes están llenos.",
          {"SEMI": -1}),
        N("Un gobierno prohíbe vender chips avanzados a su principal rival",
          "Las empresas de semiconductores pierden de golpe a su segundo mayor cliente.",
          {"SEMI": -1}, "I"),
        N("Los fabricantes de coches piden más chips de los que existen",
          "Las ventas de coches nuevos se han disparado y cada uno lleva más de mil chips. Las fundiciones trabajan "
          "a pleno rendimiento.",
          {"SEMI": 1, "AUT": 1}, "I"),
        N("Un youtuber desmonta un móvil y dice que «por dentro es precioso»",
          "El vídeo dura 47 minutos y tiene 12 millones de visitas. Al final no consiguió volver a montarlo.",
          {}),
    ],
    # ================================================================== TUR
    "TUR": [
        N("Récord de reservas de hotel para el puente",
          "Las agencias hablan de «verano adelantado»: en la costa ya no quedan habitaciones libres.",
          {"TUR": 1}),
        N("Verano de récord: el más caluroso jamás registrado",
          "48 grados a la sombra. Cierran playas y monumentos a mediodía, y muchos turistas adelantan la vuelta a "
          "casa.",
          {"TUR": -1}, "N", trap=True),
        N("Aprobada la licencia del mayor casino-resort de Asia",
          "Tendrá 4.000 habitaciones, 800 mesas de juego y aeropuerto propio. Lo gestionará una cadena del sector.",
          {"TUR": 1}, "I"),
        N("Nueva tasa turística de 15 € por noche en las principales capitales",
          "Para una familia de cuatro, una semana de hotel sale 420 € más cara.",
          {"TUR": -1}, "I"),
        N("Las aerolíneas de bajo coste anuncian 200 rutas nuevas",
          "Vuelos desde 19 € a destinos que antes no tenían conexión directa.",
          {"TUR": 1, "PTR": 1}),
        N("Brote de gastroenteritis en tres cruceros de lujo",
          "Más de 600 pasajeros afectados. Las compañías desinfectan los barcos y cancelan salidas.",
          {"TUR": -1}),
        N("Las Vegas bate su récord de visitantes",
          "Un combate de boxeo y dos conciertos llenaron todos los hoteles del bulevar. Las mesas de juego "
          "facturaron un 40% más que el año pasado.",
          {"TUR": 1}),
        N("El gobierno estudia prohibir la publicidad de los casinos",
          "Ni en televisión, ni en camisetas de fútbol, ni en internet. La ley podría votarse antes del verano.",
          {"TUR": -1}, "I"),
        N("El euro se hunde frente al dólar",
          "Para los turistas americanos, Europa nunca había estado tan barata: las búsquedas de vuelos se disparan.",
          {"TUR": 1}, "N", trap=True),
        N("Los controladores aéreos convocan huelga en pleno agosto",
          "Diez días de paros en los principales aeropuertos del país.",
          {"TUR": -1}, "I"),
        N("Una influencer dice que «este verano se lleva quedarse en casa»",
          "Lo dijo desde una piscina en Bali, con dos millones de seguidores mirando.",
          {}),
        N("Inaugurado el tren de alta velocidad entre las dos mayores ciudades",
          "Dos horas de viaje donde antes había seis. Los hoteles de ambas ciudades ya notan las primeras reservas "
          "de fin de semana.",
          {"TUR": 1}),
        N("Escándalo de amaños en los casinos de la costa",
          "La policía ha detenido a 34 personas, entre ellas varios directores de sala. Hay inspecciones por "
          "sorpresa en todos los casinos del país y cierres cautelares.",
          {"TUR": -1}, "B"),
        N("Las familias recortan en ocio por la subida de las hipotecas",
          "Una de cada tres dice que este año no se irá de vacaciones.",
          {"TUR": -1}),
        N("Un gran festival de música confirma su edición más larga",
          "Serán diez días con 200 artistas. Los hoteles de la zona ya cuelgan el cartel de completo.",
          {"TUR": 1}),
        N("Un volcán en erupción cierra el espacio aéreo de medio continente",
          "La nube de ceniza obliga a cancelar 20.000 vuelos. Los aviones se quedan en tierra y no gastan queroseno.",
          {"TUR": -1, "PTR": -1}, "I"),
        N("El país vecino elimina el visado para los turistas",
          "Bastará con el pasaporte. Las agencias preparan escapadas de fin de semana.",
          {"TUR": 1}),
        N("Los hoteles suben sus precios un 30%",
          "Y aun así no queda una habitación libre en agosto: la demanda nunca había sido tan alta.",
          {"TUR": 1}, "N", trap=True),
        N("Huelga de taxis y autobuses en el aeropuerto en plena Semana Santa",
          "Los viajeros caminan con las maletas por el arcén. Muchas reservas se cancelan a última hora.",
          {"TUR": -1}),
        N("El ministro de Turismo visita la costa en plena temporada alta",
          "Se hizo fotos con los socorristas, probó la paella del chiringuito y aseguró que «el verano va como "
          "siempre».",
          {}),
    ],
    # ================================================================== BTC
    "BTC": [
        N("Un exministro, entre los inversores de un exchange que no contesta a la prensa",
          "La plataforma lleva tres días sin publicar sus cuentas y su director no aparece por la oficina.",
          {"BTC": -1}, "I"),
        N("El mayor gestor de fondos del mundo pide permiso para un fondo de cripto",
          "Si se lo aprueban, sus 60 millones de clientes podrán comprar cripto desde su banco de siempre, con un "
          "clic.",
          {"BTC": 1}, "B"),
        N("Un país pequeño adopta la criptomoneda como moneda oficial",
          "Los funcionarios cobrarán en cripto desde el mes que viene y el banco central empezará a comprar "
          "reservas.",
          {"BTC": 1}, "I"),
        N("Hackean un puente entre cadenas: desaparecen 600 millones",
          "Los atacantes ya mueven los fondos por decenas de cuentas. Es el mayor robo del año.",
          {"BTC": -1}, "I"),
        N("Los reguladores anuncian «tolerancia cero» con las plataformas sin licencia",
          "Tendrán 30 días para registrarse o cerrar.",
          {"BTC": -1}),
        N("Se acerca el «halving»: los mineros cobrarán la mitad",
          "Cada cuatro años se reduce a la mitad la cantidad de monedas nuevas que se crean. La última vez, el "
          "precio tardó poco en notarlo.",
          {"BTC": 1}, "N", trap=True),
        N("Una marca de coches eléctricos vuelve a aceptar pagos en cripto",
          "Su consejero delegado lo anunció con un vídeo de treinta segundos. Las búsquedas de «cómo comprar cripto» "
          "se triplicaron esa tarde.",
          {"BTC": 1}),
        N("Un juez declara que ciertos tokens son valores",
          "Deberán registrarse como cualquier acción. Varias plataformas suspenden su cotización por si acaso.",
          {"BTC": -1}),
        N("Las «ballenas» mueven miles de monedas a los exchanges",
          "Los analistas de la cadena han detectado transferencias por valor de 2.000 millones a plataformas de "
          "compraventa. Nadie mueve tanto dinero a un exchange para tenerlo guardado.",
          {"BTC": -1}),
        N("Los bancos centrales lanzan su moneda digital: «lo mejor de la cripto, sin riesgos»",
          "Será igual de rápida que la cripto, pero con el respaldo del Estado y sin comisiones.",
          {"BTC": -1}, "N", trap=True),
        N("Un millonario tuitea un dibujo de un cohete",
          "Sin texto ni explicación. Tiene 400.000 «me gusta» y nadie ha averiguado qué significa.",
          {}),
        N("La inflación se dispara en un gran país emergente y su moneda se hunde",
          "Los precios suben un 8% al mes. La gente busca cualquier forma de proteger sus ahorros.",
          {"BTC": 1, "ORO": 1}),
        N("Una red eléctrica prohíbe la minería en invierno",
          "Las granjas de minado tendrán que apagarse de noviembre a marzo por falta de energía.",
          {"BTC": -1}),
        N("Los pagos con cripto superan a los de tarjeta en los casinos online",
          "Los jugadores prefieren cobrar al instante. Las plataformas de juego ya aceptan doce monedas distintas.",
          {"BTC": 1, "TUR": 1}),
        N("Un exchange anuncia «pausas temporales» en los retiros por «mantenimiento»",
          "Es el tercero más grande del mundo. Sus usuarios llevan horas intentando sacar su dinero sin éxito.",
          {"BTC": -1}, "B"),
        N("Una gran plataforma de pagos integra la cripto para 400 millones de usuarios",
          "Podrán pagar en cualquier tienda online con un botón nuevo, junto a la tarjeta.",
          {"BTC": 1}, "I"),
        N("Detienen al fundador de un exchange en un aeropuerto",
          "Intentaba salir del país con tres pasaportes. La plataforma ha suspendido todas sus operaciones.",
          {"BTC": -1}, "I"),
        N("La red de minado bate su récord histórico de potencia",
          "La competencia es tan dura que los mineros pequeños ya no cubren la factura de la luz, y venden sus "
          "monedas para poder pagarla.",
          {"BTC": -1}, "N", trap=True),
        N("Un banco tradicional, viejo enemigo de la cripto, ofrece custodiarla",
          "Su presidente la llamó «una estafa» hace tres años. Hoy la ofrece a sus clientes más ricos.",
          {"BTC": 1, "BAN": 1}),
        N("Un rapero famoso lanza su propia moneda",
          "Se llama como su perro y en la primera hora subió un 4.000%. En la segunda bajó un 99%.",
          {}),
    ],
    # ================================================================== AGR
    "AGR": [
        N("Una helada histórica arrasa los cafetales de Brasil",
          "Las temperaturas bajaron a cuatro grados bajo cero en plena zona cafetera. Se ha perdido un tercio de la "
          "cosecha y los árboles tardarán años en recuperarse.",
          {"AGR": 1}, "B"),
        N("Año de bonanza en el campo: cosecha récord de trigo",
          "Las grandes llanuras producirán un 30% más que el año pasado. Los silos no dan abasto y los "
          "compradores esperan.",
          {"AGR": -1}, "I", trap=True),
        N("El Niño amenaza con sequía en el sudeste asiático",
          "Los meteorólogos prevén lluvias un 40% por debajo de lo normal en plena temporada del arroz y del aceite "
          "de palma.",
          {"AGR": 1}, "I"),
        N("Se reabre el corredor de grano del mar Negro",
          "Los primeros cargueros salen esta semana con 3 millones de toneladas que llevaban meses en los silos.",
          {"AGR": -1}, "I"),
        N("Una plaga de langostas avanza sobre el este de África",
          "Las nubes de insectos cubren kilómetros y devoran en un día lo que comerían 35.000 personas.",
          {"AGR": 1}),
        N("Buena noticia para los agricultores: los fertilizantes cuestan la mitad",
          "Podrán abonar más sus campos esta temporada, y se espera que produzcan bastante más de lo previsto.",
          {"AGR": -1}, "N", trap=True),
        N("India prohíbe exportar arroz",
          "Es el mayor exportador del mundo. El gobierno quiere contener los precios en su mercado interno antes de "
          "las elecciones.",
          {"AGR": 1}, "I"),
        N("Lluvias perfectas en el cinturón del maíz",
          "Los analistas hablan de un «año de manual»: ni una helada, ni una sequía, ni una plaga.",
          {"AGR": -1}),
        N("Una gran cadena de cafeterías sube el café por segunda vez este año",
          "Dice que el grano le cuesta un 30% más que hace un año y que «no hay señales de que vaya a bajar».",
          {"AGR": 1}),
        N("Un hongo ataca las plantaciones de cacao de Costa de Marfil",
          "El país produce el 40% del cacao mundial. Las fábricas de chocolate revisan sus contratos.",
          {"AGR": 1}),
        N("China cancela compras de soja por valor de 3.000 millones",
          "Era el principal comprador. Los barcos que iban a cargar la soja se quedan esperando en el puerto.",
          {"AGR": -1}, "I"),
        N("Una empresa lanza una carne vegetal «indistinguible» de la real",
          "En la cata a ciegas, 7 de cada 10 periodistas la reconocieron enseguida. La empresa asegura que la "
          "próxima versión será mejor.",
          {}),
        N("Huelga de transportistas en Argentina",
          "Los camiones de grano no llegan a los puertos y los barcos esperan vacíos en la costa.",
          {"AGR": 1, "NAV": -1}),
        N("Los silos de grano europeos, al 98% de su capacidad",
          "Ya no cabe más. Algunos agricultores guardan el trigo en naves alquiladas y aceptan precios más bajos "
          "para venderlo.",
          {"AGR": -1}),
        N("Una ola de calor quema el girasol y la cebada en Europa",
          "Los campos de Castilla y del sur de Francia se han secado en apenas dos semanas.",
          {"AGR": 1}),
        N("El dólar se debilita y los compradores extranjeros acuden en masa",
          "Los cereales se pagan en dólares: para el resto del mundo, ahora salen más baratos que nunca.",
          {"AGR": 1}),
        N("Gran acuerdo para los agricultores latinoamericanos: adiós a los aranceles",
          "El azúcar y el café entrarán libres de impuestos en los grandes mercados. Se esperan envíos récord desde "
          "el mes que viene.",
          {"AGR": -1}, "N", trap=True),
        N("Aprobada una semilla que duplica el rendimiento del trigo",
          "Se podrá sembrar desde la próxima campaña. Los agricultores ya hacen cola para comprarla.",
          {"AGR": -1}),
        N("Los incendios llegan a las zonas de cultivo de California",
          "Han ardido almendros, viñedos y huertas que abastecen a medio país.",
          {"AGR": 1}),
        N("Un chef famoso dice que «el pan de antes sabía mejor»",
          "Lo dijo mientras presentaba su nuevo libro de recetas, que cuesta 89 euros.",
          {}),
    ],
    # ================================================================== AUT
    "AUT": [
        N("Retiran dos millones de coches por un fallo en los frenos",
          "La reparación será gratis para los clientes, pero costará a los fabricantes 1.800 millones.",
          {"AUT": -1}, "I"),
        N("Ayudas de 7.000 € por cambiar de coche",
          "Para cualquier coche de más de diez años que se lleve al desguace. Los concesionarios esperan colas el "
          "lunes.",
          {"AUT": 1}, "I"),
        N("El litio bate su récord histórico",
          "Las baterías costarán un 40% más el año que viene. Los fabricantes avisan de que subirán los precios de "
          "los eléctricos.",
          {"AUT": -1}, "N", trap=True),
        N("Un gigante tecnológico fabricará su propio coche",
          "Promete un eléctrico «más fácil de usar que un móvil». Llega a un mercado que ya estaba saturado.",
          {"AUT": -1}),
        N("Las ventas de coches en China crecen un 25% en un mes",
          "Las marcas extranjeras se llevan la mayor parte gracias a sus modelos más baratos.",
          {"AUT": 1}),
        N("Huelga indefinida en las tres mayores fábricas del país",
          "Las cadenas de montaje están paradas y cada día sin producir son 4.000 coches menos.",
          {"AUT": -1}, "I"),
        N("Aprobados aranceles a los coches importados",
          "Los coches extranjeros costarán un 25% más. Los fabricantes nacionales tendrán menos competencia.",
          {"AUT": 1}),
        N("Una batería que se carga en cinco minutos",
          "La presentó un fabricante europeo y llegará a sus coches el año que viene. Las gasolineras pierden su "
          "última ventaja.",
          {"AUT": 1, "PTR": -1}, "I"),
        N("Varias marcas falsearon las emisiones de sus motores",
          "Un programa secreto detectaba cuándo el coche estaba en una prueba oficial. Hay 11 millones de vehículos "
          "afectados y las multas pueden ser históricas.",
          {"AUT": -1}, "B"),
        N("Bajan los tipos y los créditos para coches se abaratan",
          "Financiar un coche de 25.000 € sale ahora 1.500 € más barato.",
          {"AUT": 1}),
        N("Faltan chips: las fábricas de coches paran líneas",
          "Los coches salen de la cadena sin terminar y esperan en las campas a que lleguen los componentes.",
          {"AUT": -1, "SEMI": 1}),
        N("La gasolina, en su precio más alto de la década",
          "Llenar el depósito cuesta ya más de 100 euros. Mucha gente aplaza la compra de un coche nuevo.",
          {"AUT": -1, "PTR": 1}),
        N("Una gran ciudad prohíbe los coches de combustión en el centro",
          "Los vecinos tienen seis meses para cambiar de coche si quieren seguir entrando.",
          {"AUT": 1}, "N", trap=True),
        N("El coche autónomo de una marca provoca un accidente grave en directo",
          "Lo estaba retransmitiendo un conocido presentador. El vídeo ha dado la vuelta al mundo.",
          {"AUT": -1}),
        N("Los concesionarios acumulan coches sin vender",
          "Algunos ya alquilan aparcamientos de centros comerciales para guardar el excedente.",
          {"AUT": -1}),
        N("Una marca china llega a Europa con un eléctrico a 15.000 €",
          "Tiene 400 km de autonomía y siete años de garantía.",
          {"AUT": -1}),
        N("Récord de matriculaciones en el mes de las rebajas",
          "Los concesionarios abren los domingos para atender a todos los clientes.",
          {"AUT": 1}),
        N("Un piloto retirado dice que «los coches de antes molaban más»",
          "Lo dijo en un programa de radio a las tres de la madrugada. Tiene una colección de 40 coches clásicos.",
          {}),
        N("El acero y el aluminio se hunden",
          "Los dos materiales básicos de la carrocería tocan mínimos de dos años. Fabricar un coche nunca había "
          "salido tan barato.",
          {"AUT": 1}, "N", trap=True),
        N("Las aseguradoras abaratan los coches con asistentes de conducción",
          "Hasta un 20% de descuento si el coche frena solo.",
          {"AUT": 1}),
    ],
    # ================================================================== BAN
    "BAN": [
        N("Malas noticias para los hipotecados: el banco central sube los tipos",
          "Medio punto más. Las cuotas subirán, pero los bancos cobrarán más por cada préstamo que ya tienen "
          "concedido.",
          {"BAN": 1}, "N", trap=True),
        N("Quiebra un banco regional tras una retirada masiva de depósitos",
          "Los clientes sacaron el 40% de su dinero en dos días. Los ahorradores de otros bancos empiezan a hacer "
          "cola en los cajeros.",
          {"BAN": -1}, "B"),
        N("Todos los grandes bancos aprueban con nota las pruebas de resistencia",
          "Aguantarían una crisis el doble de dura que la última, según el supervisor.",
          {"BAN": 1}, "I"),
        N("La morosidad de las hipotecas, en máximos de diez años",
          "Uno de cada veinte préstamos lleva más de tres meses sin pagarse.",
          {"BAN": -1}, "I"),
        N("Impuesto extraordinario sobre los beneficios bancarios",
          "El gobierno se quedará con un 30% de lo que los bancos ganen por encima de la media de los últimos años.",
          {"BAN": -1}, "I"),
        N("Se fusionan los dos mayores bancos del país",
          "Juntos tendrán uno de cada tres clientes y podrán cerrar oficinas que hoy están puerta con puerta.",
          {"BAN": 1}),
        N("Multa récord por blanqueo de capitales",
          "El banco tendrá que pagar 4.000 millones y su consejero delegado ha dimitido.",
          {"BAN": -1}),
        N("El paro cae a mínimos históricos",
          "Más gente con nómina es más gente que pide préstamos y que los devuelve.",
          {"BAN": 1}),
        N("Buenas noticias para el bolsillo: el banco central baja los tipos por sorpresa",
          "Las hipotecas y los préstamos serán más baratos. Los bancos ganarán menos con cada uno.",
          {"BAN": -1, "AUT": 1}, "N", trap=True),
        N("Los bancos digitales captan un millón de clientes al mes",
          "Sin oficinas y sin comisiones. La mitad de sus clientes tiene menos de 30 años.",
          {"BAN": -1}),
        N("Se dispara la demanda de hipotecas",
          "«La gente vuelve a comprar casa», dicen en las inmobiliarias, que han contratado más personal.",
          {"BAN": 1}),
        N("Una caída informática deja sin tarjetas a medio país",
          "Durante doce horas no se pudo pagar con tarjeta ni sacar dinero del cajero. Hay clientes cambiándose de "
          "banco.",
          {"BAN": -1}),
        N("El banco anuncia 8.000 despidos y el cierre de 1.000 oficinas",
          "Los sindicatos convocan protestas, pero la entidad calcula que ahorrará 2.000 millones al año y promete "
          "repartirlos entre sus accionistas.",
          {"BAN": 1}, "N", trap=True),
        N("Rumores de impago de una gran promotora inmobiliaria",
          "Debe 30.000 millones a los bancos y lleva dos meses sin pagar a sus proveedores.",
          {"BAN": -1}, "I"),
        N("Los bancos reparten un dividendo récord",
          "Los accionistas recibirán un 40% más que el año pasado.",
          {"BAN": 1}),
        N("Un banquero dice que «el dinero no da la felicidad»",
          "Lo dijo en su yate, durante una entrevista para una revista de decoración.",
          {}),
        N("Una ley limita las comisiones bancarias",
          "Se acabaron las comisiones por mantenimiento y por sacar dinero en cajeros de otro banco.",
          {"BAN": -1}),
        N("La economía crece el doble de lo previsto",
          "Las empresas invierten, las familias consumen y los restaurantes están llenos.",
          {"BAN": 1, "TUR": 1}),
        N("Los ahorradores abandonan la cripto y vuelven a los depósitos",
          "Después de varios sustos, muchos prefieren «menos rentabilidad y dormir tranquilos».",
          {"BAN": 1, "BTC": -1}),
        N("Un hacker roba los datos de millones de clientes de un gran banco",
          "Nombres, direcciones y movimientos de las cuentas. El banco tardó tres semanas en avisar.",
          {"BAN": -1}),
    ],
    # ================================================================== FAR
    "FAR": [
        N("Un fármaco contra el alzhéimer supera la última fase de ensayos",
          "Frena la pérdida de memoria en el 60% de los pacientes. Hay 55 millones de personas con la enfermedad y "
          "no existe ningún tratamiento parecido.",
          {"FAR": 1}, "B"),
        N("Fracasa el ensayo del medicamento estrella de la compañía",
          "Diez años de investigación y 3.000 millones invertidos: el fármaco no funciona mejor que el placebo.",
          {"FAR": -1}, "I"),
        N("Los pacientes celebran: caduca la patente del medicamento más vendido",
          "Desde mañana cualquier laboratorio podrá fabricar genéricos. El tratamiento costará una décima parte.",
          {"FAR": -1}, "I", trap=True),
        N("Aprobado un tratamiento contra la obesidad",
          "Es una inyección semanal y ya tiene lista de espera en los hospitales privados.",
          {"FAR": 1}, "I"),
        N("Brote de una gripe nueva en tres países",
          "La OMS se reúne de urgencia. Varias aerolíneas empiezan a tomar la temperatura a los pasajeros.",
          {"FAR": 1, "TUR": -1}, "I"),
        N("Precios máximos para 200 medicamentos",
          "El gobierno fija por ley cuánto podrán cobrar los laboratorios por los fármacos más recetados.",
          {"FAR": -1}),
        N("Una farmacéutica compra una empresa de biotecnología por 40.000 millones",
          "Pagará un 70% más de lo que valía en bolsa. Los analistas creen que no será la última compra del sector.",
          {"FAR": 1}),
        N("Retiran un lote de vacunas por contaminación",
          "Se han encontrado partículas extrañas en 300.000 dosis. La fábrica está bajo investigación.",
          {"FAR": -1}),
        N("Los mayores de 65 superan por primera vez a los menores de 15",
          "El país envejece más rápido de lo previsto, y con él, el gasto en medicamentos.",
          {"FAR": 1}),
        N("Una demanda colectiva por efectos secundarios ocultos",
          "Miles de pacientes acusan a la compañía de conocer los riesgos y no avisar.",
          {"FAR": -1}),
        N("Una inteligencia artificial descubre un antibiótico nuevo en una semana",
          "El laboratorio que la usa ya ha patentado la molécula.",
          {"FAR": 1}),
        N("Los genéricos indios ganan el concurso de los hospitales públicos",
          "Ofrecían los mismos medicamentos a menos de la mitad de precio.",
          {"FAR": -1}),
        N("Un famoso dice que se cura los resfriados con ajo",
          "Se come seis dientes al día. Sus vecinos de ascensor confirman que funciona, al menos para mantener la "
          "distancia.",
          {}),
        N("Buenas noticias: la OMS declara el fin de la alerta sanitaria",
          "Se acaban las campañas de vacunación de urgencia y los hospitales vuelven a la normalidad.",
          {"FAR": -1}, "N", trap=True),
        N("Las aseguradoras médicas cubrirán los tratamientos más caros",
          "Hasta ahora, muchos pacientes no podían permitírselos.",
          {"FAR": 1}),
        N("Inspección sorpresa: «deficiencias graves» en la fábrica principal",
          "La producción queda suspendida hasta nueva orden.",
          {"FAR": -1}),
        N("Una vacuna contra un tipo de cáncer muestra resultados «esperanzadores»",
          "En el primer ensayo, la mitad de los pacientes no ha recaído en dos años.",
          {"FAR": 1}),
        N("Se duplica el presupuesto de investigación médica",
          "El dinero irá a ensayos clínicos en colaboración con los laboratorios privados.",
          {"FAR": 1}),
        N("Faltan principios activos por el cierre de fábricas en Asia",
          "Varias plantas han cerrado por contaminación y los laboratorios no pueden fabricar.",
          {"FAR": -1}),
        N("La peor primavera para los alérgicos en veinte años",
          "Los niveles de polen triplican los habituales y las farmacias se quedan sin antihistamínicos.",
          {"FAR": 1}, "N", trap=True),
    ],
    # ================================================================== VRD
    "VRD": [
        N("Un país cerrará todas sus centrales de carbón en cinco años",
          "Necesitará sustituir el 30% de su electricidad, y ya ha anunciado subastas para hacerlo.",
          {"VRD": 1}, "I"),
        N("Se eliminan las subvenciones a las placas solares",
          "Desde el mes que viene, instalarlas en casa costará el doble.",
          {"VRD": -1}, "I"),
        N("Se hunden los precios de los paneles solares",
          "La sobreproducción china los abarata un 30%: montar un parque solar nunca había sido tan barato.",
          {"VRD": 1}, "N", trap=True),
        N("El gas natural se dispara por un invierno muy frío",
          "Calentar una casa cuesta el doble que el año pasado y la electricidad renovable sale más rentable que "
          "nunca.",
          {"VRD": 1, "PTR": 1}),
        N("Una semana sin viento en el norte de Europa",
          "Los molinos llevan siete días parados y hay que encender centrales de gas para cubrir la demanda.",
          {"VRD": -1}),
        N("Récord de horas de sol en el verano más seco del siglo",
          "Las placas solares no paran de producir, pero los campos de cultivo se secan.",
          {"VRD": 1, "AGR": 1}),
        N("Gran apagón: la red no soporta la producción solar del mediodía",
          "Las eléctricas tendrán que desconectar parques solares en las horas punta hasta reforzar la red.",
          {"VRD": -1}),
        N("Adjudicada la mayor subasta de eólica marina de la historia",
          "Doscientos aerogeneradores frente a la costa con contratos garantizados durante veinte años.",
          {"VRD": 1}, "I"),
        N("Suben los tipos y los proyectos verdes se encarecen",
          "Un parque eólico se paga con préstamos a veinte años: cada punto de interés lo encarece un 10%.",
          {"VRD": -1}),
        N("Una batería que guarda la energía solar para la noche",
          "Cuesta la mitad que las actuales y dura veinte años. «El sol ya no se pone», presume su inventora.",
          {"VRD": 1}, "B"),
        N("La cumbre del clima termina sin acuerdo",
          "Tras dos semanas de reuniones, los países solo se comprometen a «seguir hablando».",
          {"VRD": -1}),
        N("Un tribunal paraliza tres parques eólicos para proteger a un ave",
          "El águila perdicera anida en la zona. Las obras no podrán continuar en años.",
          {"VRD": -1}),
        N("El petróleo se desploma a mínimos de dos décadas",
          "Llenar el depósito y calentar la casa con gasóleo sale más barato que nunca, y muchos proyectos solares "
          "dejan de salir a cuenta.",
          {"VRD": -1, "PTR": -1}, "I", trap=True),
        N("Un activista se pega a un cuadro en un museo",
          "El cuadro estaba protegido por un cristal. El activista tardó dos horas en despegarse.",
          {}),
        N("Las tecnológicas alimentarán sus centros de datos con energía verde",
          "Han firmado contratos por diez años con varias eléctricas renovables.",
          {"VRD": 1, "SEMI": 1}),
        N("Un tifón destroza un parque solar flotante",
          "Las placas han aparecido a varios kilómetros de la costa. La aseguradora estudia el caso.",
          {"VRD": -1}),
        N("Placas solares obligatorias en todos los edificios nuevos",
          "La norma entra en vigor en enero y afecta también a las naves industriales.",
          {"VRD": 1}),
        N("Falta cobre: los cables para conectar los parques eólicos tardan un año",
          "Hay 40 parques terminados que no pueden verter electricidad a la red.",
          {"VRD": -1}),
        N("Una central nuclear nueva, lista antes de lo previsto",
          "Producirá electricidad limpia y constante, sin depender del sol ni del viento, para cuatro millones de "
          "hogares.",
          {"VRD": -1}, "N", trap=True),
        N("Las eléctricas tradicionales pagan una fortuna por parques renovables",
          "Las tres mayores compiten por comprar todo lo que sale a la venta.",
          {"VRD": 1}),
    ],
    # ================================================================== VID
    "VID": [
        N("El juego más esperado de la década se retrasa otra vez",
          "El estudio pide «un poco más de paciencia». Es el tercer retraso en dos años.",
          {"VID": -1}, "I"),
        N("Una nueva consola se agota en 4 minutos",
          "Las tiendas online se colapsaron y la reventa ya pide el triple de su precio.",
          {"VID": 1, "SEMI": 1}, "I"),
        N("Se filtra el código fuente de la saga estrella del estudio",
          "Los tramposos ya preparan sus programas para el juego en línea.",
          {"VID": -1}),
        N("El juego gratuito del estudio supera los 100 millones de jugadores",
          "Uno de cada cinco ya ha comprado algo dentro del juego. Es el lanzamiento más rentable de la historia del "
          "sector.",
          {"VID": 1}, "B"),
        N("Estudian prohibir las cajas de botín por considerarlas apuestas",
          "Los juegos que las incluyan tendrían que retirarlas o venderse solo a mayores de edad.",
          {"VID": -1}, "I"),
        N("El estudio despide a 2.000 desarrolladores",
          "Cancela sus proyectos menos prometedores para centrarse en sus sagas más rentables. Ahorrará 400 "
          "millones al año.",
          {"VID": 1}, "N", trap=True),
        N("Una serie basada en un juego del estudio arrasa",
          "Es la más vista del año en las plataformas, y las ventas del juego original se han multiplicado por diez.",
          {"VID": 1}),
        N("La crítica destroza el último lanzamiento",
          "Nota media de 4 sobre 10. Los jugadores piden la devolución del dinero.",
          {"VID": -1}),
        N("Un torneo de deportes electrónicos llena un estadio",
          "60.000 personas viendo a diez jugadores sentados delante de un ordenador. Los hoteles de la ciudad, "
          "completos.",
          {"VID": 1, "TUR": 1}),
        N("La mayor tienda digital sube su comisión al 40%",
          "Se quedará con casi la mitad de cada juego que se venda en ella.",
          {"VID": -1}),
        N("Los jugadores boicotean los micropagos",
          "Miles de reseñas negativas en un solo día por una espada que costaba 25 euros.",
          {"VID": -1}),
        N("Un streamer famoso dice que se aburre de jugar",
          "Lo dijo en directo, durante una partida de nueve horas.",
          {}),
        N("Vacaciones de verano: las descargas se triplican",
          "Los servidores del estudio baten su récord de jugadores conectados a la vez.",
          {"VID": 1}),
        N("Un gigante tecnológico quiere comprar el estudio",
          "Ofrece un 50% más de lo que vale en bolsa. El consejo de administración «estudiará la oferta».",
          {"VID": 1}, "I"),
        N("Unos hackers tumban los servidores en el fin de semana de lanzamiento",
          "Nadie ha podido jugar en línea durante tres días. Las tiendas aceptan devoluciones.",
          {"VID": -1}),
        N("Se hunde el precio de las tarjetas gráficas",
          "Cuestan la mitad que hace un año y los jugadores aprovechan para renovar sus ordenadores.",
          {"VID": 1, "SEMI": -1}, "N", trap=True),
        N("China limita a tres horas semanales el juego de los menores",
          "Es el mayor mercado del mundo para el estudio.",
          {"VID": -1}, "I"),
        N("El estudio anuncia el remake de su clásico de los 90",
          "El tráiler tiene 30 millones de visitas en un día.",
          {"VID": 1}),
        N("Una demanda por patentes amenaza con retirar el juego de las tiendas",
          "Una empresa desconocida dice haber inventado el sistema de saltos del juego.",
          {"VID": -1}),
        N("Éxito sorpresa en las tiendas: un juego hecho por dos personas arrasa",
          "Ha vendido más que la gran producción del estudio, que costó 300 millones y salió la misma semana.",
          {"VID": -1}, "N", trap=True),
    ],
}
